---
title: "Worksheet 7a"
author: "Kirby Clarence Alegoria"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
#install.packages("Hmisc")
#install.packages("pastecs")
```

```{r}
#1. Create a data frame for the table below. Figure 1: Student Scores
```

```{r}
student <- seq(1:10)
    preTest <- c(55,54,47,57,51,61,57,54,63,58)
    postTest <- c(61,60,56,63,56,63,59,56,62,61)

    DataFr <- data.frame(student,preTest,postTest)
    DataFr
```

```{r}
#a. Compute the descriptive statistics using different packages 
#   (Hmisc and pastecs). Write the codes and its result.
```

```{r}
library(Hmisc)
library(pastecs)

    #describe(DF)

    #stat.desc(DF)
```

```{r}
#2. The Department of Agriculture was studying the effects of several levels of 
#   a fertilizer on the growth of a plant. For some analyses, it might be useful 
#   to convert the fertilizer levels to an ordered factor.
```

```{r}
 DepartmentofAgriculture <- c(10,10,10,20,20,50,10,
                                 20,10,50,20,50,20,10)

    #a. Write the codes and describe the result.
    
    Order <- sort(DepartmentofAgriculture, decreasing = FALSE)
    Order
```

```{r}
   #Based on the result, the fertilizer levels were sorted from the lowest 
   #to the highest value.
```

```{r}
#3. Abdul Hassan, president of Floor Coverings Unlimited, has asked you to study
#   the exercise levels undertaken by 10 subjects were “l”, “n”, “n”, “i”, “l” ,
#   “l”, “n”, “n”, “i”, “l” ; n=none, l=light, i=intense
    
#a. What is the best way to represent this in R?
```

```{r}
#   The best way to represent this is through dataframe.
    
    exercise_levels <- c("l","n","n","i","l","l","n","n","i","l")
    
    exerciselvl <- data.frame(exercise_levels)
    exerciselvl
    
    exerlvl <- data.frame(
      none = c("n", "n", "n", "n"),
      light = c("l", "l", "l", "l"),
      intense = c("i", "i", "NA", "NA")
    )
    exerlvl
```

```{r}
#4. Sample of 30 tax accountants from all the states and territories of 
#   Australia and their individual state of origin is specified by a character 
#   vector of state mnemonics as:
```

```{r}
    state <- c("tas", "sa", "qld", "nsw", "nsw", "nt", "wa", "wa", "qld",
               "vic", "nsw", "vic", "qld", "qld", "sa", "tas", "sa", "nt",
               "wa", "vic", "qld", "nsw", "nsw", "wa", "sa", "act", "nsw",
               "vic", "vic", "act")
    state 
```

```{r}
#a. Apply the factor function and factor level. Describe the results.

    factorfunc <- function(state)
    factorfunc
```

```{r}
#5. From #4 - continuation:
  
# Suppose we have the incomes of the same tax accountants in another vector 
# (in suitably large units of money)
```

```{r}
    incomes <- c(60, 49, 40, 61, 64, 60, 59, 54, 62, 69, 70, 
                 42, 56, 61, 61, 61, 58, 51, 48, 65, 49, 49, 
                 41, 48, 52, 46, 59, 46, 58, 43)
```

```{r}
  #a. Calculate the sample mean income for each state we can now use the special
   #    function tapply():
```

```{r}
    cal <- tapply(state, incomes, mean)
    cal
```

```{r}
  #b. Copy the results and interpret.
  #    40 41 42 43 46 48 49 51 52 54 56 58 59 60 61 62 64 65 69 70 
  #    NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
```

```{r}
#6. Calculate the standard errors of the state income means 
    #(refer again to number 3)
```

```{r}
    calcustd.n <- length(cal)
    calculate.sd <- sd(cal)
    calstd.se <- calculate.sd/sqrt(calcustd.n)
    calstd.se
```

```{r}
    #a. What is the standard error? Write the codes.
    #   The result of the code above is NA.
```

```{r}
   #b. Interpret the result.
   #   The result is not available for the reason that the other objects are 
   #   classified as character type, therefore it won't be able to get 
   #   the standard error.
```

```{r}
#7. Use the titanic dataset.
```

```{r}
    data("Titanic")
  
    titanset<- data.frame(Titanic)
    titanset
```

```{r}
  #a. subset the titatic dataset of those who survived and not survived. 
  #   Show the codes and its result.
```

```{r}
        Sbset <- subset(titanset, select = "Survived")
        Sbset
```

```{r}
#8. The data sets are about the breast cancer Wisconsin. The samples arrive 
#   periodically as Dr. Wolberg reports his clinical cases. The database 
#   therefore reflects this chronological grouping of the data. You can create 
#   this dataset in Microsoft Excel.
```

```{r}
  #a. describe what is the dataset all about.
  #   The dataset is all about Breast Cancer Wisconsin.
```

```{r}
  #b. Import the data from MS Excel. Copy the codes.
```

```{r}
library("readxl")
  DATA <- read_excel("C:/Users/acer/Documents/BSIT-2A/WorkSheet#7a/Breast_Cancer.xlsx")
  DATA
```

```{r}
  #c. Compute the descriptive statistics using different packages. 
  #   Find the values of:
```

```{r}
  #c.1 Standard error of the mean for clump thickness.
       clump <- length(DATA$`CL. thickness`)
       clump1 <- sd(DATA$`CL. thickness`)
       clump2 <- clump1/sqrt(DATA$`CL. thickness`)
       clump2
```

```{r}
  #c.2 Coefficient of variability for Marginal Adhesion.
       COV <- sd(DATA$`Marg. Adhesion`) / mean(DATA$`Marg. Adhesion`)* 100
       COV
```

```{r}
  #c.3 Number of null values of Bare Nuclei.
       null_values <- subset(DATA,`Bare. Nuclei` == "NA")
```

```{r}
  #c.4 Mean and standard deviation for Bland Chromatin
       mean(DATA$`Bl. Cromatin`)
       sd(DATA$`Bl. Cromatin`)
```

```{r}
  #c.5 Confidence interval of the mean for Uniformity of Cell Shape
  
     #Calculate the mean
       confInterMean <- mean(DATA$`Cell Shape`)
       confInterMean
```

```{r}
     #Calculate the standard error of the mean
       stdErrMean <- length(DATA$`Cell Shape`)
       stdB <- sd(DATA$`Cell Shape`)
       result <- stdB/sqrt(stdErrMean)
       result
```

```{r}
     #Find the t-score that corresponds to the confidence level
       tscore = 0.05
       num1 = stdErrMean - 1
       num2 = qt(p = tscore/ 2, df = num1,lower.tail = F)
       num2
```

```{r}
     #Constructing the confidence interval
       num3 <- num2 * num1
```

```{r}
     #LOWER
       num4 <- stdErrMean - num3
```

```{r}
     #UPPER
       num5 <- stdErrMean + num3
```

```{r}
       num6 <- c(num4,num5)
       num6
```

```{r}
     #d. How many attributes?
         attributes(DATA)
```

```{r}
     #e. Find the percentage of respondents who are malignant. 
     #   Interpret the results.
         percResp <- subset(DATA, Class == "maligant")
         percResp
```

```{r}
     #There 17 respondents who are malignant.
     #And there are total of 49 respondent.
```

```{r}
     #Getting the percentage
         percenTage <- 17 / 49 * 100
         percenTage
```

```{r}
#9. Export the data abalone to the Microsoft excel file. Copy the codes.
```

```{r}
        #install.packages("AppliedPredictiveModeling")
```

```{r}
library("AppliedPredictiveModeling")
  
        data("abalone")
        View(abalone)
        head(abalone)
        summary(abalone)
```

```{r}
        #Exporting the data abalone to the Microsoft excel file.
          #install.packages("xlsxjars")
```

```{r}
library(xlsx)
  write.xlsx("abalone","C:/Users/acer/Documents/BSIT-2A/WorkSheet#7a/abalone.xlsx")


```

