---
title: "Worksheet 3"
author: "Kirby Clarence Alegoria BSIT 2-A"
date: "`r Sys.Date()`"
output: pdf_document
---
```{r}
#Using Vectors
```

```{r}
#a. You need to produce a vector that contains the first 11 letters.
LETTERs <- c('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K')
LETTERs
```


```{r}
#b. Produce a vector that contains the odd numbered letters.

LETTERS <- c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", 
             "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z")
LETTERS
LETTERS2 <- LETTERS[1:26 %% 2 !=0]
LETTERS2
```

```{r}
#c.	Produce a vector that contains the vowels. Based on the above vector 
#   letters:

LETTER1 <- LETTERS[c(1, 5, 9, 15, 21)]
LETTER1
```


```{r}
#d. Based on the above vector letters produce a vector that contains the last 5 
#   lowercase letters.  

letters <- c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n",
             "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z")
letters

Lowercase <- letters[c(22, 23, 24, 25, 26)]
Lowercase
```

```{r}
#e. Produce a vector that contains letters between 15 to 24 letters in lowercase.

Lowercase2 <- letters[c(16, 17, 18, 19, 20, 21, 22, 23)]
Lowercase2
```

```{r}
#2. Create a vector with the average temperatures in April for Tuguegarao City, Manila,
#   Iloilo City, Tacloban, Samal Island, and Davao City. The average temperatures in
#   Celcius are 42, 39, 34, 34, 30, and 27 degrees.

#a. What is the R code and its result for creating a character vector for the city/town of
#   Tuguegarao City, Manila, Iloilo City, Tacloban, Samal Island, and Davao City? Name the
#   object as city. The names should follow the same order as in the instruction.

city <- c("Tuguegarao_City", "Manila", "Iloilo_City", "Tacloban", "Samal_Island", "Davao City")
city 
```

```{r}
#b. The average temperatures in Celcius are 42, 39, 34, 34, 30, and 27 degrees. 
#   Name the object as temp.
#   Write the R code and its output. Numbers should also follow what is in the instruction.

temp <- c(42, 39, 34, 34, 30, 27)
temp
```

```{r}
#c. Associate the temperature temp with the city by using names() function. What is
#   the R code and its result?

names(temp) <- city
temp
```

```{r}
#e. From the answer in d, what is the content of index 5 and index 6? What is its R code?

names1 <- temp[5:6]
names1
```

```{r}
#Using Matrices
```

```{r}
#2. Create a matrix of one to eight and eleven to fourteen with four columns and three rows.

#a. What will be the R code for the #2 question and its result?

Table1 <- matrix(c(1:8, 11:14), nrow = 3, ncol = 4)
Table1
```

```{r}
#b. Multiply the matrix by two. What is its R code and its result?

output <- Table1*2
output
```

```{r}
#c. What is the content of row 2? What is its R code?

content <- c(Table1[2,1], Table1[2,2], Table1[2,3], Table1[2,4])
content
```

```{r}
#d. What will be the R code if you want to display the column 3 and column 4 in row 1
#   and row 2? What is its output?

content <- c(Table1[1,3], Table1[1,4], Table1[2,3], Table1[2,4])
content
```

```{r}
#e. What is the R code is you want to display only the columns in 2 and 3, row 3? 
#   What is its output?

content <- c(Table1[3,2], Table1[3,3])
content
```

```{r}
#f. What is the R code is you want to display only the columns 4? What is its output?

content <- c(Table1[1,4], Table1[2,4], Table1[3,4])
content
```

```{r}
#g. Name the rows as isa, dalawa, tatlo and columns as uno, dos, tres, quatro
#   for the matrix that was created in b.‘. What is its R code and corresponding output?

dimnames(output) <- list(c("isa", "dalawa", "tatlo"),c("uno", "dos", "tres", "quatro"))
output
```

```{r}
#h. From the original matrix you have created in a, reshape the matrix by assigning a
#   new dimension with dim(). New dimensions should have 2 columns and 6 rows. What will
#   be the R code and its output?
  
dim(Table1) <- c(6,2)
Table1
```

```{r}
#Using Arrays
```

```{r}
#3. An array contains 1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1

#a. Create an array for the above numeric values. Each values will be repeated twice
#   What will be the R code if you are to create a three-dimensional array with 
#   4 columns and 2 rows. What will be its output?

arr <- c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1)
arr

arr2 <- array(rep(arr, 2), dim = c(2,4,3))
arr2
```

```{r}
#b. How many dimensions do your array have? 
#    It has three dimensions

dim(arr2)
```



```{r}
#c. Name the rows as lowercase letters and columns as uppercase letters starting from
#   the A. The array names should be “1st-Dimensional Array”, “2nd-Dimentional Array”, and
#   “3rd-Dimensional Array”. What will be the R codes and its output?

dimnames(arr2) <- list(letters[1:2], LETTERS[1:4], c("1st-Dimensional Array", 
"2nd-Dimensional Array", "3rd-Dimensional Array"))
arr2
```
